Remove unoconv check in validateform because it will always fail on servers with open_basedir restrictions in place
systopia/de.systopia.civioffice pull request #73
Opened 2024-11-13 17:56 UTC by mattwire

file_exists() and other similar functions will always fail on eg. /usr/bin/unoconv because it is not allowed to access system files when open_basedir restrictions are in place.

2025-02-27 12:54 UTC, jensschuppe commented
I'm not sure we want to just remove that check. CiviCRM Core has been doing [the same e.g. for wkhtmltopdf](https://github.com/civicrm/civicrm-core/blob/8759714a994796e832a2063d37f5404f18e62ac2/CRM/Admin/Form/Setting/Miscellaneous.php#L154-L159) and we should not leave it completely unvalidated.

2025-02-28 08:25 UTC, dontub commented
What about trying to execute `$unoconv_binary_path --version` and check if the exit code is `0`?

2025-03-05 11:18 UTC, jensschuppe commented
Actually there already is this very version check in the renderer type's `isReady()` method, so we actually could as well remove the hard check for `file_exists()` in the form validation.

2025-03-05 11:24 UTC, jensschuppe requested changes

2025-03-05 11:24 UTC, jensschuppe commented on CRM/Civioffice/DocumentRendererType/LocalUnoconv.php
> +        //}
Lets remove the check altogether and add a more elaborate comment.
```suggestion
        // There used to be a file_exists() check here for validating that the unoconv binary exists in the given path.
        // We can't however check eg. /usr/bin/unoconv on a site with open_basedir restrictions in place as this check
        // would always fail. There is a check running `unoconv --version` in the isReady() method() which implicitly
        // covers the validation of the unconv binary being accessible.
```

2025-03-05 14:02 UTC, dontub commented
> Actually there already is this very version check in the renderer type's `isReady()` method, so we actually could as well remove the hard check for `file_exists()` in the form validation.

`isReady()` isn't called on validation, is it? IMHO there should be a validation when entering the configuration, not sometime later.

2025-03-05 14:25 UTC, jensschuppe commented
> IMHO there should be a validation when entering the configuration, not sometime later.

That sounds reasonable on first thought, but the binary is not guaranteed to be there when it is actually used, so the form validation is not reliable enough in the first place. The `isReady()` method is being called after saving the form as well, so you will see that something is wrong right away.

We could have a follow-up to actually show *what* is not ready, but not checking with `file_exists()` is solving a bug, so I'd say that's good enough for now.

2025-03-10 22:04 UTC, mattwire commented on CRM/Civioffice/DocumentRendererType/LocalUnoconv.php
> +        //}
Thanks @jensschuppe I accepted your change and squashed commits

2025-03-10 22:04 UTC, mattwire commented
@jensschuppe I've accepted your change to the comment and rebased/squashed - is this ok now?

2025-03-11 13:43 UTC, merged

2025-03-11 13:45 UTC, jensschuppe commented
Thanks @mattwire! I just corrected my own typo in the comment :wink: